name: wtf_on_docker_DEV

services:

    db_postgres:
        image: postgres:14-alpine
        container_name: wtf_postgres_ctr
        ports: 
            - 5433:5432
        environment:
            - POSTGRES_DB=${POSTGRES_DB}
            - POSTGRES_USER=${POSTGRES_USER}
            - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
        #restart: always
        restart: unless-stopped
        volumes:
            - postgres_data:/var/lib/postgresql/data
        command: postgres -c listen_addresses='*' #for opening the container from outside
    
    wtf:
        #image: my_wtf_image
        build: .    # This tells Docker Compose to build the Docker image from the current directory
        container_name: wtf_django_ctr
        # command: /bin/bash -c " sleep 10 && 
        #                         python manage.py makemigrations && 
        #                         python manage.py migrate && 
        #                         python manage.py createsuperuser --noinput && 
        #                         python manage.py runserver 0.0.0.0:8000"
        command: /bin/bash -c " sleep 10 && 
                                python manage.py makemigrations && 
                                python manage.py migrate && 
                                python manage.py runserver 0.0.0.0:8000"                                
        ports: 
            - 8001:8000
        restart: unless-stopped
        volumes:
            - wtf_data:/wtf_app
        environment:
            - DJANGO_SUPERUSER_USERNAME=${DJANGO_SUPERUSER_USERNAME}
            - DJANGO_SUPERUSER_PASSWORD=${DJANGO_SUPERUSER_PASSWORD}
            - DJANGO_SUPERUSER_EMAIL=${DJANGO_SUPERUSER_EMAIL}
            - DJANGO_RUNTIME=${DJANGO_RUNTIME}
            - DJANGO_ENV=${DJANGO_ENV}
            - DJANGO_SECRET_KEY=${DJANGO_SECRET_KEY}
            - POSTGRES_DB=${POSTGRES_DB}
            - POSTGRES_USER=${POSTGRES_USER}
            - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
        depends_on:
            - db_postgres
            
    tasks:
        build: .
        #command: /bin/bash -c "sleep 20 && python manage.py makemigrations && python manage.py migrate && python manage.py process_tasks"
        command: /bin/bash -c "sleep 30 && 
                               python manage.py process_tasks"
        container_name: wtf_tasks_ctr
        volumes:
            - wtf_data:/wtf_app
        environment:
            - DJANGO_ENV=${DJANGO_ENV}
            - DJANGO_RUNTIME=${DJANGO_RUNTIME}
            - POSTGRES_DB=${POSTGRES_DB}
            - POSTGRES_USER=${POSTGRES_USER}
            - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}        
        depends_on:
            - wtf
        restart: unless-stopped

volumes:
    postgres_data:
    wtf_data: