# Generated by Django 4.2.15 on 2025-01-03 14:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='default_credentials',
            name='Password',
            field=models.CharField(blank=True, default='', max_length=120, null=True),
        ),
        migrations.AlterField(
            model_name='default_credentials',
            name='Username',
            field=models.CharField(blank=True, default='', max_length=120, null=True),
        ),
    ]
