# Generated by Django 4.2.15 on 2025-03-21 11:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_alter_global_settings_max_capture_age_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ACL_Most_Expanded',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('HostName', models.CharField(blank=True, default='', max_length=120, null=True)),
                ('ACL_Line', models.TextField()),
                ('ACL_ELength', models.PositiveBigIntegerField(blank=True, default=0, null=True)),
            ],
            options={
                'verbose_name': 'ACL_Most_Expanded',
                'verbose_name_plural': 'ACL_Most_Expanded',
                'db_table': 'ACL_Most_Expanded',
                'managed': True,
            },
        ),
    ]
