# Generated by Django 4.2.15 on 2025-03-21 14:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_acl_most_hitpermit'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ACL_Most_HitPermit',
        ),
    ]
