# Generated by Django 4.2.15 on 2025-03-24 13:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_delete_acl_most_hitpermit'),
    ]

    operations = [
        migrations.CreateModel(
            name='Top_IP_Range',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('HostName', models.CharField(blank=True, default='', max_length=120, null=True)),
                ('Obj_Name', models.CharField(blank=True, default='', max_length=130, null=True)),
                ('IP_Range_Length', models.PositiveBigIntegerField(blank=True, default=0, null=True)),
            ],
            options={
                'verbose_name': 'Top_IP_Range',
                'verbose_name_plural': 'Top_IP_Range',
                'db_table': 'Top_IP_Range',
                'managed': True,
            },
        ),
    ]
