# Generated by Django 4.2.15 on 2025-03-24 21:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0007_top_ip_range'),
    ]

    operations = [
        migrations.CreateModel(
            name='Top_ICMP_Open_Detail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('HostName', models.CharField(blank=True, default='', max_length=120, null=True)),
                ('ACL_Line', models.TextField(blank=True, default='', null=True)),
                ('ICMP_Open_Val', models.PositiveBigIntegerField(blank=True, default=0, null=True)),
            ],
            options={
                'verbose_name': 'Top_ICMP_Open_Detail',
                'verbose_name_plural': 'Top_ICMP_Open_Detail',
                'db_table': 'Top_ICMP_Open_Detail',
                'managed': True,
            },
        ),
    ]
