# Generated by Django 4.2.15 on 2025-03-24 22:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0010_alter_top_tcp_open_detail_tcp_open_val'),
    ]

    operations = [
        migrations.AlterField(
            model_name='top_tcp_open_detail',
            name='TCP_Open_Val',
            field=models.DecimalField(blank=True, decimal_places=0, default=0, max_digits=50, null=True),
        ),
    ]
