# Generated by Django 4.2.15 on 2025-04-15 18:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0012_top_ip_open_detail_top_udp_open_detail'),
    ]

    operations = [
        migrations.AlterField(
            model_name='acl_gross',
            name='HostName',
            field=models.TextField(db_index=True),
        ),
    ]
