# Generated by Django 4.2.24 on 2025-09-22 10:04

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0014_my_devices_hardware_my_devices_sw_version'),
    ]

    operations = [
        migrations.CreateModel(
            name='Bad_News',
            fields=[
                ('ID', models.SmallAutoField(primary_key=True, serialize=False)),
                ('HostName', models.CharField(blank=True, default='', max_length=120, null=True)),
                ('Tmiestamp', models.DateField(blank=True, default=datetime.date(2000, 1, 1), null=True)),
                ('Content', models.TextField(blank=True, default='', null=True)),
                ('Flag', models.BooleanField(default=False)),
            ],
            options={
                'verbose_name': 'Bad_News',
                'verbose_name_plural': 'Bad_News',
                'db_table': 'Bad_News',
                'managed': True,
            },
        ),
    ]
